P2/GGL/Ejercicio_1_GGL.c, P2/GGL/Ejercicio_2_GGL.c, P2/GGL/Ejercicio_3_GGL.c
Si salio :sob: :sob: :sob: , si era lo del archivo, por que salia como HTML.
=> [SOCKETS EN C][GGL][REDES]

P2/OMM/cliente_Ej1_OMM.c, P2/OMM/encrypt_Ej1_OMM.c, P2/OMM/servidor_Ej1_OMM.c
[SOCKETS EN C][OMM][REDES]
Dificultad de la practica: 
Definitivamente fue mas facil que la practica I, ya que la practica I era un nivel mas arriba, me explico, aqui programamos computadoras, pero en la anterior programamos redes de ellas.
=> [PRACTICA II SOCKETS][OMM][REDES]

P2/CHE/Ejercicio_1_CHE.c, P2/CHE/Ejercicio_2_CHE.c, P2/CHE/Ejercicio_3_CHE.c, P3/CHE/Ejercicio_1_CHE.c, P3/CHE/Ejercicio_2_CHE.c, P3/CHE/Ejercicio_3_CHE.c, P3/CHE/Ejercicio_4_CHE.c
1.  Cifrado César: Código sencillo ya que solo se tuvo que sumar el desplazamiento en vez de restarlo.
2.  Identificador de palíndromos:  Código sencillo ya que el fgets puede aplicarse a una variedad de aplicaciones.
3.  Información del servidor: Código más demandante por el esfuerzo de investigación sobre los diversos comandos para obtener información determinada del sistema.
=> [SOCKETS EN C][CHE][REDES]

P2/MGFJ/Ejercicio_1_MGFJ.c, P2/MGFJ/Ejercicio_2_MGFJ.c, P2/MGFJ/Ejercicio_3_MGFJ.c
Los ejercicios considero que no fueron tan complicados, salvo el tercero. Para el primer ejercicio simplemente se invirtió el signo para el desplazamiento y agregue un pequeño menú para usarlo, para el segundo simplemente se definió el tamaño de la entrada del usuario y usando la función fgets() se recuperaba la entrada del usuario y se mostraba y finalizaba el programa, para el tercero, como no tengo muchos conocimientos en C, si tuve que buscar más para poder realizarlo.
En general la dificultad de la práctica tal y como está considero que está bien, no es demasiado complicada dado que el documento PDF que nos dan si es una guía de mucha utilidad, pero tampoco es tan sencilla, ya que si hay que entenderla bien y buscar un poco por nuestra cuenta para poder realizarla.
=> [SOCKETS EN C][MGFJ][REDES]

P2/MMG/Ejercicio1_MMG.c, P2/MMG/Ejercicio2_MMG.c, P2/MMG/Ejercicio3_MMG.c, P2/MMG/client.c
Considero que los ejercicios no fueron tan complicados. 
Para el primer ejercicio solo bastó con invertir el signo del decrypt y agregué el main para que funcionara correctamente. 
Para el segundo ejercicio únicamente necesitaba entender cómo funcionaba fgets, lo cual se resolvió fácilmente buscando información. 
El tercer ejercicio requirió un poco más de comandos de Linux, pero con paciencia se logró armar el sysinfo.txt con todos los datos que pedía la práctica.
Pero la practica es muy clara, las instrucciones son claras y si se sigue al pie de la letra sale correctamente.
=> [SOCKETS EN C][mmg][REDES]

P2/LARE/Ejercicio_1_LARE.c, P2/LARE/Ejercicio_1_LARE.h, P2/LARE/Ejercicio_2_LARE.c, P2/LARE/readme.txt, P2/LARE/server.c
Leve confusion con la parte practica referente a la funcion a agregar en server.c
=> [SOCKETS EN C][LARE][REDES]

P2/PAAB/Ejercicio1PAAB.c, P2/PAAB/Ejercicio2PAAB.c, P2/PAAB/Ejercicio3PAAB.c
Estuvo un poco complicada, pero no como la practica1
=> [SOCKETS EN C][PAAAB][REDES]

P2/RSAA/Ejercicio_1_RSAA.c, P2/RSAA/Ejercicio_2_RSAA.c, P2/RSAA/Ejercicio_3_RSAA.c
Tuve que leer la especificación de la práctica muchas veces para entenderle, pero luego de eso la realización de los ejercicios estuvo sencilla.
=> [SOCKETS EN C][rsaa][REDES]

P2/RTDB/client.c, P2/RTDB/fgets.c, P2/RTDB/server.c
=> [Practica 2][RTDB][Redes]

P2/GGEB/Ejercicio_1_GGEB.c, P2/GGEB/Ejercicio_2_GGEB.c
=> [SOCKETS][ggeb][REDES]

P3/CCVM/client.c, P3/CCVM/clientMulti.c, P3/CCVM/server.c, P3/CCVM/serverOpt.c, P4/PA/CCVM/client.c, P4/PA/CCVM/server.c
El primer ejercicio (serverOpt) lo sentí un poco laborioso, ya que tuve que aprender a usar la función y definición poll, por lo que adaptar el código para usarlo fue un poco complicado. En cuanto al ejercicio 2 (clientMulti) fue más sencillo el adaptarlo, pues ya manejaba multiples ports y multiples sockets, así que solo hizo falta compacatar un poco más el código y adaptarlo a la funcionalidad de la entrada requerida
=> [CLIENTE-SERVIDOR][CCVM][REDES]

P2/OMFA/Ejercicio1_server_OMFA.c, P2/OMFA/Ejercicio_client_OMFA.c, P3/FAOM/Ejercicio1_FAOM_serverOpt.c, P3/FAOM/Ejercicio2_FAOM_clientMult.c
Las dificultades habían estado en la práctica anterior, esta mediante la conexión ssh permitió que todo fuera un tanto más sencillo.
=> [CLIENTE SERVIDOR][OMFA][REDES].

P3/SUC/Ejercicio_1_SUC.c, P3/SUC/Ejercicio_2_SUC.c, P3/SUC/Ejercicio_3_SUC.c, P3/SUC/Ejercicio_4_SUC.c
La práctica me costó al principio (sobre todo entender bien los sockets y el “header” que mandé entre cliente y servidor), pero al final logré que el cliente hablara con varios servidores y que solo el puerto correcto procesara el texto con el cifrado César. Lo más enredado fue manejar bien las longitudes del contenido, limpiar el archivo a solo letras, y hacer pruebas en varias terminales/VMs.
=> [CLIENTE-SERVIDOR][SUC][REDES]

P2/SGPY/client.c, P2/SGPY/server.c, P3/clientMulti_ej1_SGPY.c, P3/serverOpt_ej1_SGPY.c
Se agrergan los archivos c de la práctica 3
=> [PRACTICA3:CLIENTE-SERVIDOR][SGPY][REDES]

P3/FMM/Ejercicio_1_FMM.c, P3/FMM/Ejercicio_2_FMM.c, P3/FMM/Ejercicio_3_FMM.c, P3/FMM/Ejercicio_4_FMM.c
Los ejercicios de cliente y servidor fueron los más tardados, ya con esa base salían relativamente fácil los otros.
=> [CLIENTE-SERVIDOR][FMM][REDES]

P3/AMSG/client.c, P3/AMSG/clientMulti.c, P3/AMSG/server.c, P3/AMSG/serverOpt.c
El segundo ejercicio (del cliente) estuvo relativamente mas sencillo que el primero (en lo que entendia como crear las conexiones con multiples puertos, que lo termine haciendo sin hilos)
Los detalles de la implementacion de ambos estan en mi pdf
=> [CLIENTE-SERVIDOR][AMSG][REDES]

P3/MHPM/clientMulti.c, P3/MHPM/serverOpt.c
Estuvo más complicada que la anterior, en especial hacer que el cliente recibiera múltiples puertos y que a la vez se pudieran mandar diferentes archivos.
=> [CLIENTE-SERVIDOR][MHPM][REDES]

P3/MMVM/Client.c, P3/MMVM/Server.c, P3/MMVM/clientMulti.c, P3/MMVM/serverOpt.c
=> [CLIENTE-SERVIDOR][MMVM][REDES]

P4/PA/JDA/client.c, P4/PA/JDA/server.c
la parte que mas se me complicó fue la de configurar los alias de mi red, pues en la práctica dice que usemos la 192.168.0.100, pero mi red no está mapeada con esa, tuve que usar 192.168.1.100 (si dice, pido disculpas, XD), respecto a las modificaciones, el que mas cambios tuvo fue mi server, pues lo tenía hecho muy raro
=> [SERVIDOR CON ALIAS PARTE A][JDA][REDES].

P4/PA/LARE/client.c, P4/PA/LARE/server.c
MAS VALE TARDE QUE NUNCA
- Debo decir que fue interesante como funcionaron los alias en ubuntu ya cuando tenemos configurado los alias en debian, pense que seria similar su configuracion, pero resulto ser mas sencillo de lo que pensaba
- Tuve demasiados fallos con enviar los archivos (mi demora principal) y hubo algo dentro del archivo .sh que tuve que modificar (no lo agregue ni cambie en este commit), pues hubo problemas con como pasaba el archivo, esta fue la linea extra que agregie antes de ejecutar ./client:
FILE=$(echo "$FILE" | tr -d '\r\n')
=> [SERVIDOR CON ALIAS PARTE A][LARE][REDES]

P4/PA/AMSG/client.c, P4/PA/AMSG/server.c
Tuve que usar las alias IPs 192.168.1.101 y 192.168.1.102 en vez de 192.168.0.101 y 192.168.0.101. 
NO los encontraba la otra MV con ping
=>  [MULTIPORT_PARTE_A][AMSG][REDES]

P4/PA/FMM/client.c, P4/PA/FMM/server.c
La parte para poder conectar el servidor y el cliente si se me complico bastante y fue en lo que más me tarde.
=> [SERVIDOR CON ALIAS][FMM][REDES]

P3/HAJA/Ejercicio_1_HAJA.c, P3/HAJA/cliente.c, P3/HAJA/clienteMulti.c, P3/HAJA/server.c, P3/HAJA/serverOpt.c, P3/HAJA/texto.txt, P3/HAJA/texto2.txt, P3/HAJA/texto3.txt, P4/PA/HAJA/cliente.c, P4/PA/HAJA/server.c
Practica complicada, tardada, pero estuvo buena.
=> [SERVIDOR CON ALIAS PARTE A][HAJA][REDES]

P4/PA/VADJ/client.c, P4/PA/VADJ/server.c
Esta parte de la práctica realizarla me parecio mas simple que las prácticas pasadas, sobre todo que la anterior debido a que ya hay un poco más de familiaridad. Por otro lado entender lo que estaban solicitando en la práctica me costo mucho, me maree con el documento.
Nota: cambie las ip de como venian en el documento, porque la ip de mi casa es 192.168.100 y no me dejaba conectar el cliente con el server sin ese cambio
=> [SERVIDOR CON ALIAS PARTE A][VADJ][REDES]

P2/DBASA/Ejercicio_1_DBASA.c, P2/DBASA/Ejercicio_2_DBASA.c, P2/DBASA/Ejercicio_3_DBASA.c
Una disculpa por la demora en la entrega de los ejercicios en Git, espero puedan ser aceptados como comentamos por privado.
Los ejercicios me parecieron sencillos, la práctica sirve como una gran base para resolverlos, mi único inconveniente fue el ejercicio 3, donde fui incapáz de guardar la información en dos archivos diferentes del lado del cliente.
=> [SOCKETS EN C][DBASA][REDES]

P4/PA/GCAM/client.c, P4/PA/GCAM/server.c
La parte mas dificil de esta practica fue la conexion entre el servidor y el cliente, ademas en mi caso se me trababa mis maquinas virutales e iban muy lentas (por mi compu jejej), pero ya para el codigo no me costo tanto su implementacion.
=> [SERVIDOR CON ALIAS PARTE A][GCAM][REDES]

P3/RDLI/client.c, P3/RDLI/clientMulti.c, P3/RDLI/server.c, P3/RDLI/serverOpt.c, P4/PA/RDLI/client.c, P4/PA/RDLI/sender.sh, P4/PA/RDLI/server.c, P4/PB/RDLI/client.c, P4/PB/RDLI/sender.sh, P4/PB/RDLI/server.c
Modifique el archvio del cliente y el servidor para ajustarse a los requerimientos
=> [SERVIDOR CON ALIAS ][RDLI][REDES]

P4/PB/client.c, P4/PB/server.c
esta parte de la práctica fue mucho mas fácil, pues configurar los nuevos alias fue muy sencillo una vez sabia que tenia que hacer, y respecto a los archivos, hacer que el cliente ahora se conectara a los demás servidores fue relativamente sencillo, pues la lógica era la misma solo que se aplicaba a los otros 3 servidores.
=> [SERVIDOR CON ALIAS PARTE B][JDA][REDES]

P4/PB/LARE/client.c, P4/PB/LARE/server.c
- Debo decir que no fue complicado, utilice de base los ejercicios de la practica pasada y utilice parte del codigo de la parte A de esta practica para poder realizar dichos archivos.
- Lo mas tardado fue que tuve un error en el que los alias nuevos (s03 y s04) no estaban funcionando, a pesar de que al usar ping s03 funcionaba o utilizar 'netstat -tuln | grep 49200' si detectaba los puertos con sus ip's, reiniciando las maquinas virtuales fue que dejo de darme ese error, pero el tratar de buscar algo dentro del codigo que pudiera estar provocando esto fue lo que me consumio tiempo.
=> [SERVIDOR CON ALIAS PARTE B][LARE][REDES]

P4/PA/ABG/server.c, P4/PB/ABG/log_cliente.txt, P4/PB/ABG/sender_b.sh
- Se modificaron client.c y server.c para recibir y guardar archivos
- Se creó sender_b.sh para envíos aleatorios con log
- Se generó log_cliente.txt con detalles de los envíos
=> [SERVIDOR CON ALIAS PARTE B][ABG][REDES]

P4/PB/CHE/client.c, P4/PB/CHE/conectar.sh, P4/PB/CHE/server.c
Como la parte A la hice pensando en los cambios de la parte B solo tuve que modificar ligeramente los archivos c pero tuve que agregar un script de bash para simular el client status.
Borren el commit de [YamilSalazar] ya que al aceptarla se repetió la carpeta la práctica IV
=> [SERVIDOR CON ALIAS PARTE B][CHE][REDES]

P4/PB/GGEB/Client.c, P4/PB/GGEB/Server.c
Esta parte estuvo un poco mas rapida que la parte A, pero estuvo muy entretenida
=> [SERVIDOR CON ALIAS PARTE B][GGEB][REDES]

P4/PB/MMVM/ClienteP4.c, P4/PB/MMVM/ServerP4.c
Todo salio bien con la prática (o eso espero jaja). No tuve mucho problema para la implementación de la parte B y ya no he tenido broncas con las ip's.
=> [SERVIDOR CON ALIAS PARTE B][MMVM][REDES]

P4/PB/ABEI/Ejercicio_server_ABEI.c, P4/PB/ABEI/Ejericicio_client_ABEI.c
Para la parte B no tuve que hacerle mayores cambios a los archivos server y client ya que ya para la conexión, envío y recepción de archivos es similar a la Parte A, y solo se requiere levantar los servidores en los nuevos alias configurados.
=> [SERVIDOR CON ALIAS PARTE B][ABEI][REDES]

P4/PB/MHPM/client.c, P4/PB/MHPM/server.c
En general no tuve que hacer grandes cambios a los códigos de la parte A, traté de corregir la parte de bash y hacer que se comunicaran de manera correcta al usar los 4 alias
=> [SERVIDOR CON ALIAS PARTE B][MHPM][REDES]

P4/PB/RLSV/client.c, P4/PB/RLSV/send.sh, P4/PB/RLSV/server.c
Me costó arreglar "Address already in use"  al intentar crear el socket de las direcciones. 
Pero además de esto, ya fue más fácil por sólo reusar el código de la parte A.
=> [SERVIDOR CON ALIAS PARTE B][RLSV][REDES]

solutions/README.md, solutions/VADJ_EULER_5.c
Elegi el ejercicio 5 porque me pareció sencillo, consiste en buscar el multiplo más pequeño entre una serie de numeros, me dedique unicamente a resolver la instancia del problema particular en C
=> [ADDED][VADJ][PRE_5]

solutions/MGFJ_EULER_89.py, solutions/README.md
Decidí hacer el ejercicio 89, por que inicialmente comencé haciendo uno de una dificultad muy alta (SET, No recuerdo el número :C), pero no lo entendí muy bien, entonces, decidí realizar uno con una dificultad más baja, pero que me quedara claro cómo hacerlo al cien por ciento, este ejercicio me pareció interesante ya que consiste en simplificar representaciones de números romanos a la versión con menos caracteres posibles y regresar el resultado (caracteres ahorrados) de la entrada inicial en comparación a la representación mínima.
El archivo que se utilice y que la página proporciona para verificar la solución propuesta está en el siguiente link:
https://projecteuler.net/resources/documents/0089_roman.txt
=> [ADDED][MGFJ][PRE_89]

solutions/GCJ_Euler_7.c, solutions/README.md
Para esta práctica, realicé el ejercicio 7 de project Euler en C.
=> [ADDED][GCJ][PRE_7]

solutions/CCVM_EULER_56.py, solutions/README.md
Realicé el ejercicio 56 usando python. Además agrego mi github al readme.
=> [ADDED][CCVM][PRE_56]

solutions/ASAJ_Euler_79.c, solutions/README.md
La sincronización de repositorios y todo respecto a dejar limpio nuestro espacio de trabajo es bastante interesante pero confuso las primeras veces que lo haces. Además tenía miedo de moverle a algo que no debía. El ejercicio estuvo desafiante, me gustó porque la solución es una gráfica y recordé mucho de lo visto en las clases.
=> [ADDED][ASAJ][PRE_79]

solutions/JGAE_EULER_67.c, solutions/README.md
Intenté agregarme hasta el final con la versión más actualizada.
Me gustó esto de resolver ejercicios y sí tuve que investigar mucho de git para todo esto de los conflictos.
=> [ADDED][JGAE][PRE_67]

solutions/GCAM_EULER_20.c, solutions/README.md
El ejercicio no fue tan dificil, la parte que si se me complico fue lo de git, ya que, aunque hiciera sync fork no aparecia la rama, entonces tuve que hacer unos pasos de mas para poder crearla con todo lo relacionado
=> [ADDED][GCAM][PRE_20]

solutions/GGEB_Euler_2.py, solutions/GGEB_Euler_76.py, solutions/README.md
Me gusto el ejercicio que escogi, aunque al inicio parecia sencillo, si tuve buscar una solución mas optimizada para el problema
=> [ADDED][GGEB][PRE_76].

solutions/FMM_EULER_48.c, solutions/README.md
Este ejercicio me recordó a un ejercicio que hicimos en lenguajes donde comparamos como Java y python mandaba stack overflow cuando tratabamos de calcular 1000000^1000000, sin embargo con Haskell no pasaba eso.
=> [ADDED][FMM][PRE_48]

solutions/BLMA_EULER_18.c, solutions/README.md
Se añadio el ejercicio 18 y modificacion de README
=> [ADDED][BLMA][PRE_18]

solutions/MHPM_EULER_686.c, solutions/README.md
Lo que me costó del ejercicio fue optimizar el código, ya que al tener un número demasiado grande para procesar, el programa tardaba demasiado en compilar. 
Por otra parte igual me costó un poco subir los cambios, ya que no había usado Sync Fork.
=> [ADDED][MHPM][PRE_686]

solutions/README.md, solutions/SUC_EULER_31.cpp
El ejercicio fue bastante sencillo ya que la solución del problema es una variante clásica de programación dinámica, el famosísimo Knapsack. Por lo que la implementación fue directa ya que he resuelto este tipo de problemas varias veces en el pasado.
=> [ADDED][SUC][PRE_31]

solutions/GGL_EULER_69.c, solutions/README.md
📖 Descripción
Este Pull Request agrega mi solución al problema 69 (Totient maximum) de Project Euler, como parte de la práctica de redes.
🛠️ Cambios Realizados
Se agregó el archivo GGL_EULER_69.c con la implementación en C.
Se actualizó el archivo README.md con mi nombre y enlace a mi perfil de GitHub.
🔍 Notas
El algoritmo implementado calcula la función φ de Euler para encontrar el valor de n que maximiza la razón n/φ(n). Para n ≤ 1,000,000, la solución correcta es 510510.
=> [ADDED][GGL][PRE_69]

P5/VTD/client.c, P5/VTD/server.c
La compilacion de server.c se debe hacer con 'gcc server.c -o server -lpthread' y la ejecucion como la practica anterior './server s01 s02 ...'. Para el caso de client, se mantiene igual la compilacion con gcc y su ejecucion con './client ...'.
=> [RESTRICCION DE SERVIDOR][VTD][REDES]

P5/GGEB/p5_server.c
Estuvo muy corta la practica, pero si talachuda con el codigo
=> [RESTRICCIÓN DE SERVIDOR][GGEB][REDES]

P5/CTAR/client.c, P5/CTAR/server.c
Sin duda esta practica ha sido la más difícil hasta el momento. El manejo de los hilos con distintos servidores y puertos dificultó mucho las cosas. También manejar la memoria compartida adecuadamente del lado del servidor presentó un desafió. Se tiene que hacer un buen uso de la memoria y los procesos para que no consuman muchos recursos. En cliente hubo que hacer unos cambios a la versión de P4A para que pudiera enviar varios archivos.
En general tuve varios problemas manejando el encolamiento de cada servidor para evitar que el cliente terminará y así esperé una respuesta que no sea REJECTED directamente.
=> [RESTRICCIÓN DE SERVIDOR][CTAR][REDES]

solutions/README.md, solutions/SGPY_EULER_11.py
Se agrega modificación a README y el ejercicio 11 de proyecto EULER
=> [ADDED][SGPY][PRE_11]

P5/ASAJ/client.c, P5/ASAJ/server.c
El implementar el algoritmo de Round Robin para el servidor fue sin duda alguna retador, pues tuve que añadir conexiones no bloqueantes, variables compartidas e investigar más a fondo  el lenguaje de programación y el algoritmo en cuestión. Con todos estos cambios me ha funcionado correctamente y cada servidor espera en una fila cíclica para recibir los archivos del cliente. Fue de gran ayuda el código ya implementado. Más detalles en el reporte.  
Hago este PR un poco prematuro por si hay detalles que se necesiten corregir, espero no sea contraproducente.
=> [RESTRICCIÓN DE SERVIDOR][ASAJ][REDES]

solutions/README.md, solutions/RI_EULER_34.c
Hola, perdon por la tardanza, soy el chico que ha estado enfermo, el dia de hoy ya me siento un poco mejor, y voy terminando la practica, no estuvo tardada, sin emvbargo me sigo sintiendo mal por lo que tuve que ir haciendo pausas, muchas gracias.
=> [ADDED][RI][PRE_34]
